# all paths are relative to this file

debug: False

# paths
output_path: './'

# providers from which to search (case insensitive)
providers:
  - 'Indeed'
  - 'Monster'
  - 'GlassDoor'

# filters
search_terms:
  region:
    province: 'ON'
    city:     'waterloo'
    domain:   'ca'
    radius:   10

  keywords:
    - 'Python'

black_list:
  - 'Infox Consulting'
  - 'Terminal'

# logging level options are: critical, error, warning, info, debug, notset
log_level: 'info'

# saves duplicates removed by tfidf filter to duplicate_list.csv
save_duplicates: False

# delaying algorithm configuration
delay_config:
    # functions used for delaying algorithm, options are: constant, linear, sigmoid
    function: 'linear'
    # maximum delay/upper bound for converging random delay
    delay: 10
    # minimum delay/lower bound for random delay
    min_delay: 1
    # random delay
    random: True
    # converging random delay, only used if 'random' is set to True
    converge: True
